# Generated by Django 4.0.6 on 2022-08-02 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carosel')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders_products', to='main.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders_options', to='main.options'),
        ),
        migrations.AlterField(
            model_name='products',
            name='main_img',
            field=models.ImageField(upload_to='products/main'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_img',
            field=models.ImageField(upload_to='products/sub'),
        ),
    ]
